name: Release iOS SDK

on:
  push:
    branches:
      - main
    paths:
      - VERSION

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: macos-latest-xlarge
    outputs:
      release_version: ${{ steps.version-file.outputs.release-version }}
      release_notes: ${{ steps.get-changelog.outputs.release_notes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: "16.2"

      - name: Get current version
        id: version-file
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT

      - name: Get changelog content
        id: get-changelog
        uses: ffurrer2/extract-release-notes@cae32133495112d23e3569ad04fef240ba4e7bc8 # v2.3.0
        with:
          changelog_file: CHANGELOG.md

      - name: Build xcframework
        run: ./scripts/build_xcframework_zip.sh

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          tag_name: ${{ steps.version-file.outputs.release-version }}
          name: Release ${{ steps.version-file.outputs.release-version }}
          make_latest: true
          body: |
            Release ${{ steps.version-file.outputs.release-version }}
            ## Changelog
            ${{ steps.get-changelog.outputs.release_notes }}
          files: vendor/Rokt_Widget.xcframework.zip

  publish-cocoapods:
    needs: build-and-release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Validate Podspec
        run: pod spec lint Rokt-Widget.podspec --allow-warnings --verbose

      - name: Publish to CocoaPods
        run: pod trunk push Rokt-Widget.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  trigger-demo-app-release:
    needs: [build-and-release, publish-cocoapods]
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.SDK_RELEASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.SDK_RELEASE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: rokt-demo-ios

      - name: Dispatch Event
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ROKT/rokt-demo-ios
          event-type: release-build
          client-payload: |
            {
              "version_name": "${{ needs.build-and-release.outputs.release_version }}",
              "release_notes": ${{ toJSON(needs.build-and-release.outputs.release_notes) }}
            }
